### ISSUE TITLE
No default :ex_cldr backend is configured when calling `known_territories`

### ISSUE THREAD

**Issue by thiagomajesk** [elixir-cldr/cldr_territories#45]
Hi! Thanks for the amazing work with this lib... I was reviewing this old code today and I noticed that when calling `known_territories` I get an exception: `No default :ex_cldr backend is configured`. The same doesn't happen when calling `known_languages`... IIRC configuring the backend in `config.exs` is discouraged and I don't remember it being necessary 🤔.

```elixir
defmodule MyBackend.Cldr do
  use Cldr,
    locales: ["en", "pt"],
    default_locale: "en",
    providers: [Cldr.Language, Cldr.Territory]

  def language_options() do
    languages = __MODULE__.Language.known_languages()

    languages
    |> Enum.map(fn {key, %{standard: name}} -> {name, key} end)
    |> Enum.sort()
  end

  def valid_languages() do
    languages = __MODULE__.Language.known_languages()
    Enum.map(languages, fn {key, _} -> to_string(key) end)
  end

  def location_options() do
    territories = __MODULE__.Territory.known_territories()

    territories
    |> Enum.map(fn {key, %{standard: name}} -> {name, key} end)
    |> Enum.sort()
  end

  def valid_locations() do
    territories = __MODULE__.Territory.known_territories()
    Enum.map(territories, fn {key, _} -> to_string(key) end)
  end
end
```

Here's the mix file:

```elixir
 {:ex_cldr, "~> 2.38"},
 {:ex_cldr_languages, "~> 0.3.3"},
 {:ex_cldr_territories, "~> 2.7"}
```

**Comment by Schultzer** [comment]
Hey @thiagomajesk, apologize for this late response, but are you still seeing this issue, I believe this error is coming from  `:ex_cldr` and not this library.

**Comment by MarkoH17** [comment]
I'm seeing the same error message:
```
iex(1)> MyApp.Territory.from_territory_code(:GB)
** (Cldr.NoDefaultBackendError) No default :ex_cldr backend is configured
    (ex_cldr 2.40.2) lib/cldr/config/config.ex:383: Cldr.Config.default_backend/0
    (ex_cldr 2.40.2) lib/cldr.ex:608: Cldr.put_default_locale/1
    (ex_cldr 2.40.2) lib/cldr.ex:536: Cldr.default_locale/0
    (my_app 0.11.0) deps/ex_cldr_territories/lib/cldr/backend.ex:230: MyApp.Cldr.Territory.from_territory_code/2
```

Mix file:
```
{:ex_cldr, "~> 2.40"},
{:ex_cldr_numbers, "~> 2.33"},
{:ex_cldr_territories, "~> 2.9.0"}
```

config.exs:
```elixir
config :my_app, MyApp.Cldr, locales: ["en"]
```

cldr.ex
```elixir
defmodule MyApp.Cldr do
  use Cldr,
    default_locale: "en",
    locales: ["en"],
    add_fallback_locales: false,
    gettext: MyApp.Gettext,
    data_dir: "./priv/cldr",
    otp_app: :my_app,
    providers: [Cldr.Territory],
    generate_docs: true,
    force_locale_download: false
end
```

Any ideas on how to troubleshoot this?

**Comment by Schultzer** [comment]
> I'm seeing the same error message:
> 
> ```
> iex(1)> MyApp.Territory.from_territory_code(:GB)
> ** (Cldr.NoDefaultBackendError) No default :ex_cldr backend is configured
>     (ex_cldr 2.40.2) lib/cldr/config/config.ex:383: Cldr.Config.default_backend/0
>     (ex_cldr 2.40.2) lib/cldr.ex:608: Cldr.put_default_locale/1
>     (ex_cldr 2.40.2) lib/cldr.ex:536: Cldr.default_locale/0
>     (my_app 0.11.0) deps/ex_cldr_territories/lib/cldr/backend.ex:230: MyApp.Cldr.Territory.from_territory_code/2
> ```
> 
> Mix file:
> 
> ```
> {:ex_cldr, "~> 2.40"},
> {:ex_cldr_numbers, "~> 2.33"},
> {:ex_cldr_territories, "~> 2.9.0"}
> ```
> 
> config.exs:
> 
> config :my_app, MyApp.Cldr, locales: ["en"]
> cldr.ex
> 
> defmodule MyApp.Cldr do
>   use Cldr,
>     default_locale: "en",
>     locales: ["en"],
>     add_fallback_locales: false,
>     gettext: MyApp.Gettext,
>     data_dir: "./priv/cldr",
>     otp_app: :my_app,
>     providers: [Cldr.Territory],
>     generate_docs: true,
>     force_locale_download: false
> end
> Any ideas on how to troubleshoot this?


To debug this we would have to look at the last line in the stack trace: [ex_cldr_territories/lib/cldr/backend.ex:230](https://github.com/elixir-cldr/cldr_territories/blob/5fb2d84cfd999d8ca6ceecede4406f17b06ae7bf/lib/cldr/backend.ex#L230)

There we see a call to `Cldr.get_locale()`. When I execute that in iex I get the same error raised:

```
iex(2)> Cldr.get_locale()
** (Cldr.NoDefaultBackendError) No default :ex_cldr backend is configured
    (ex_cldr 2.40.2) lib/cldr/config/config.ex:383: Cldr.Config.default_backend/0
    (ex_cldr 2.40.2) lib/cldr.ex:608: Cldr.put_default_locale/1
    (ex_cldr 2.40.2) lib/cldr.ex:536: Cldr.default_locale/0
    iex:2: (file)
```

We can conclude that the issue is not in this library but is caused by a configuration error.

https://github.com/elixir-cldr/cldr_territories/blob/5fb2d84cfd999d8ca6ceecede4406f17b06ae7bf/config/test.exs#L5
```
config :ex_cldr,
  default_locale: "en-001",
  default_backend: TestBackend.Cldr
```


@kipcole9 I think Cldr.Config.default_backend could serve a better error message or even register the backend module in the use macro when compiling.


@tozz, @thiagomajesk and @MarkoH17, I'm going to close this a resolved; I've had a lot on my plate lately
